# Generated by Django 4.2.1 on 2024-04-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0002_agriculture_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='chercheur',
            fields=[
                ('id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('test', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Policy_Maker',
            fields=[
                ('id', models.BigAutoField(default=0, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('test', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
