# Generated by Django 4.2.1 on 2024-04-26 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0003_chercheur_policy_maker'),
    ]

    operations = [
        migrations.CreateModel(
            name='field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('boundaries', models.CharField(max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.agriculture')),
            ],
        ),
    ]
