# Generated by Django 4.2.1 on 2024-04-26 14:29

from django.db import migrations, models
import django.db.models.deletion
import models_only.models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0005_alter_agriculture_id_alter_chercheur_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=30)),
                ('vatiety', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('saison_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.saison')),
            ],
        ),
        migrations.CreateModel(
            name='soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[(models_only.models.Soil_type['Loam'], 'Loam'), (models_only.models.Soil_type['Sandy'], 'Sandy soil'), (models_only.models.Soil_type['Clay'], 'Clay'), (models_only.models.Soil_type['Silty'], 'Silty'), (models_only.models.Soil_type['Peat'], 'Peat soil'), (models_only.models.Soil_type['Black'], 'Black soil'), (models_only.models.Soil_type['Arid'], 'Arid soil')], max_length=20)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
        ),
        migrations.CreateModel(
            name='Pratique_Agricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('quantite', models.IntegerField()),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.crop')),
            ],
        ),
        migrations.CreateModel(
            name='irrigation_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrigation_type', models.CharField(max_length=50)),
                ('debit', models.IntegerField()),
                ('instalation_date', models.DateField()),
                ('Maintenance_date', models.DateField()),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
        ),
    ]
