# Generated by Django 4.1.11 on 2024-06-10 22:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import models_only.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=30)),
                ('vatiety', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'verbose_name': 'farmer',
                'verbose_name_plural': 'farmers',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('boundaries', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Irrigation_system',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('irrigation_type', models.CharField(max_length=50)),
                ('debit', models.IntegerField()),
                ('instalation_date', models.DateField()),
                ('Maintenance_date', models.DateField()),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
        ),
        migrations.CreateModel(
            name='Ogimet_stations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('lat', models.CharField(max_length=50)),
                ('long', models.CharField(max_length=50)),
                ('location_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyMaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Searcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(choices=[(models_only.models.Soil_type['Loam'], 'Loam'), (models_only.models.Soil_type['Sandy'], 'Sandy soil'), (models_only.models.Soil_type['Clay'], 'Clay'), (models_only.models.Soil_type['Silty'], 'Silty'), (models_only.models.Soil_type['Peat'], 'Peat soil'), (models_only.models.Soil_type['Black'], 'Black soil'), (models_only.models.Soil_type['Arid'], 'Arid soil')], max_length=20)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(blank=True, null=True)),
                ('coordinates', models.CharField(max_length=50)),
                ('station_type', models.CharField(max_length=20)),
                ('sensor_type', models.CharField(max_length=20)),
                ('mesur', models.IntegerField()),
                ('field_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Soil_analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PH_eau', models.FloatField()),
                ('EC_ms_cm', models.FloatField()),
                ('EC_ms_cm_pate_saturée', models.FloatField()),
                ('Argile', models.FloatField()),
                ('Limon', models.FloatField()),
                ('Sable', models.FloatField()),
                ('MO', models.FloatField()),
                ('Nt', models.FloatField()),
                ('P205', models.FloatField()),
                ('K20', models.FloatField()),
                ('Na20', models.FloatField()),
                ('Na', models.FloatField()),
                ('Cao', models.FloatField()),
                ('Ca', models.FloatField()),
                ('MGo', models.FloatField()),
                ('Mg', models.FloatField()),
                ('SAR', models.FloatField()),
                ('Cu', models.FloatField()),
                ('Mn', models.FloatField()),
                ('Fe', models.FloatField()),
                ('Zn', models.FloatField()),
                ('NNH4', models.FloatField()),
                ('NO3', models.FloatField()),
                ('CI', models.FloatField()),
                ('BORE', models.FloatField()),
                ('Caco3', models.FloatField()),
                ('Caco3_actif_AXB', models.FloatField()),
                ('soil_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.soil')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
        ),
        migrations.CreateModel(
            name='Remote_sensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(blank=True, null=True)),
                ('path', models.CharField(max_length=50)),
                ('RS_type', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('field_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pratique_Agricole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('quantite', models.IntegerField()),
                ('crop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Maitenance_dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('irrigation_system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.irrigation_system')),
            ],
        ),
        migrations.CreateModel(
            name='Lidar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(blank=True, null=True)),
                ('test', models.CharField(max_length=20)),
                ('field_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(blank=True, null=True)),
                ('test', models.CharField(max_length=20)),
                ('field_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='saison_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models_only.season'),
        ),
    ]
