# Generated by Django 4.1.11 on 2024-06-07 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='test',
        ),
        migrations.RemoveField(
            model_name='policymaker',
            name='test',
        ),
        migrations.RemoveField(
            model_name='searcher',
            name='test',
        ),
    ]
