# Generated by Django 4.1.11 on 2024-06-04 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='saison',
            new_name='Season',
        ),
    ]
