# Generated by Django 4.1.11 on 2024-07-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigation_system',
            name='irrigation_type',
            field=models.CharField(choices=[('Sprinkler', 'Sprinkler irrigation'), ('Surface', 'Surface irrigation'), ('Drip', 'Drip irrigation'), ('Rainfed', 'Rainfed irrigation')], max_length=20),
        ),
    ]
