# Generated by Django 4.1.11 on 2024-07-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0002_alter_irrigation_system_irrigation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drip_irrigation',
            name='Dripers_distance',
        ),
        migrations.AddField(
            model_name='drip_irrigation',
            name='Drippers_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drip_irrigation',
            name='Tubes_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drip_irrigation',
            name='drippers_area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soil',
            name='soil_type',
            field=models.CharField(choices=[('SILT', 'SILT'), ('LOAMY_SAND', 'LOAMY SAND'), ('SAND', 'SAND'), ('SANDY_LOAM', 'SANDY LOAM'), ('LOAM', 'LOAM'), ('SANDY_CLAY_LOAM', 'SANDY CLAY LOAM'), ('CLAY_LOAM', 'CLAY LOAM'), ('SILTY_CLAY', 'SILTY CLAY'), ('SANDY_CLAY', 'SANDY CLAY'), ('CLAY', 'CLAY')], max_length=20),
        ),
    ]
