# Generated by Django 4.1.11 on 2024-07-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0003_remove_drip_irrigation_dripers_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='saison_id',
            new_name='Season',
        ),
        migrations.AlterField(
            model_name='crop',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='vatiety',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
