# Generated by Django 4.1.11 on 2024-07-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0004_rename_saison_id_crop_season_alter_crop_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='end_date',
        ),
        migrations.AddField(
            model_name='crop',
            name='tree',
            field=models.BooleanField(default=False),
        ),
    ]
