# Generated by Django 4.1.11 on 2024-07-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0005_remove_season_end_date_crop_tree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='crop_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='tree',
            new_name='value',
        ),
        migrations.RenameField(
            model_name='crop',
            old_name='vatiety',
            new_name='variety',
        ),
    ]
