# Generated by Django 4.2.1 on 2024-04-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0006_crop_soil_pratique_agricole_irrigation_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(blank=True, null=True)),
                ('coordinates', models.CharField(max_length=50)),
                ('station_type', models.CharField(max_length=20)),
                ('sensor_type', models.CharField(max_length=20)),
                ('mesur', models.IntegerField()),
                ('field_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Remote_sensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(blank=True, null=True)),
                ('path', models.CharField(max_length=50)),
                ('RS_type', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('field_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models_only.field')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
