# Generated by Django 4.1.11 on 2024-07-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0006_rename_crop_type_crop_type_rename_tree_crop_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='value',
            field=models.CharField(max_length=30),
        ),
    ]
