# Generated by Django 4.1.11 on 2024-07-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0007_alter_crop_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fao_Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=20)),
                ('Kcbini', models.FloatField()),
                ('Kcbmid', models.FloatField()),
                ('Kcbend', models.FloatField()),
                ('Lini', models.FloatField()),
                ('Ldev', models.FloatField()),
                ('Lend', models.FloatField()),
                ('hmax', models.FloatField(blank=True)),
                ('Zrmax', models.FloatField(blank=True)),
                ('pbase', models.FloatField(blank=True)),
            ],
        ),
    ]
