# Generated by Django 4.2.1 on 2024-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0008_ogimet_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogimet_stations',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
