# Generated by Django 4.1.11 on 2024-07-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0008_fao_parametre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fao_parametre',
            name='Ldev',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fao_parametre',
            name='Lend',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fao_parametre',
            name='Lini',
            field=models.FloatField(blank=True),
        ),
    ]
