# Generated by Django 4.2.1 on 2024-04-28 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0009_alter_ogimet_stations_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ogimet_stations',
            name='id_station',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
