# Generated by Django 4.1.11 on 2024-07-30 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0009_alter_fao_parametre_ldev_alter_fao_parametre_lend_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fao_Parametre',
            new_name='Fao_Crop_Parametre',
        ),
    ]
