# Generated by Django 4.2.1 on 2024-04-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0010_ogimet_stations_id_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ogimet_stations',
            old_name='id_station',
            new_name='station_id',
        ),
    ]
