# Generated by Django 4.1.11 on 2024-07-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0010_rename_fao_parametre_fao_crop_parametre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Kcbend',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Kcbini',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Kcbmid',
            field=models.FloatField(blank=True),
        ),
    ]
