# Generated by Django 4.1.11 on 2024-07-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0011_alter_fao_crop_parametre_kcbend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Kcbend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Kcbini',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Kcbmid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Ldev',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Lend',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Lini',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='Zrmax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='hmax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fao_crop_parametre',
            name='pbase',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
