# Generated by Django 4.1.11 on 2024-07-30 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0012_alter_fao_crop_parametre_kcbend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KCB_Crop_Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(max_length=20)),
                ('Kcbini', models.FloatField(blank=True, null=True)),
                ('Kcbmid', models.FloatField(blank=True, null=True)),
                ('Kcbend', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fao_Crop_Parametre',
        ),
    ]
