# Generated by Django 4.1.11 on 2024-07-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0013_kcb_crop_parametre_delete_fao_crop_parametre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fao_Crop_Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=20)),
                ('Kcbini', models.FloatField(blank=True, null=True)),
                ('Kcbmid', models.FloatField(blank=True, null=True)),
                ('Kcbend', models.FloatField(blank=True, null=True)),
                ('Lini', models.FloatField(blank=True, null=True)),
                ('Ldev', models.FloatField(blank=True, null=True)),
                ('Lmid', models.FloatField(blank=True, null=True)),
                ('Lend', models.FloatField(blank=True, null=True)),
                ('Zrini', models.FloatField(default=0.05)),
                ('zrmax', models.FloatField(blank=True, null=True)),
                ('pbase', models.FloatField(blank=True, null=True)),
                ('Ze', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='Sol_Fao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sol', models.CharField(max_length=20)),
                ('REW', models.FloatField(blank=True, null=True)),
                ('thetaFC', models.FloatField(blank=True, null=True)),
                ('thetaWP', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='KCB_Crop_Parametre',
        ),
    ]
