# Generated by Django 4.1.11 on 2024-07-31 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0014_fao_crop_parametre_sol_fao_delete_kcb_crop_parametre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sol_Fao',
            new_name='Sol_Fao_Parametre',
        ),
    ]
