# Generated by Django 4.1.11 on 2024-08-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0015_rename_sol_fao_sol_fao_parametre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sol_fao_parametre',
            old_name='thetaFC',
            new_name='thetaFC_max',
        ),
        migrations.RenameField(
            model_name='sol_fao_parametre',
            old_name='thetaWP',
            new_name='thetaFC_min',
        ),
        migrations.AddField(
            model_name='sol_fao_parametre',
            name='thetaWP_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sol_fao_parametre',
            name='thetaWP_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
