# Generated by Django 4.1.11 on 2024-08-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_only', '0016_rename_thetafc_sol_fao_parametre_thetafc_max_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sol_fao_parametre',
            old_name='REW',
            new_name='REW_max',
        ),
        migrations.AddField(
            model_name='sol_fao_parametre',
            name='REW_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
